version: '3'

services:
  web1:
    image:  nicopaez/password-api
    ports:
      - "3001:3000"
  web2:
    image:  nicopaez/password-api
    ports:
      - "3002:3000"
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on: 
      - web1
      - web2

    